### ISSUE TITLE
Please provide a readme

### ISSUE THREAD

**Issue by anselmbradford** [RSPB/CloudForest#1]

**Comment by tracek** [comment]
Thanks! I wrote a short description for the files. Do let me know if you think that some information is missing.

**Comment by anselmbradford** [comment]
Thank you! That does help a lot to know what's happening in this repo. Perhaps include installation instructions or at least link to the GEE Playground and/or instructions.

**Comment by tracek** [comment]
Sorry for the late reply, totally missed your message. I updated the readme, hopefully making the repository more useful.

**Comment by anselmbradford** [comment]
Looks good! Thank you!
